version: '3.4'

services:
  bot:
    build:
      context: .
      args:
        COOKIE:
    environment:
      BOT_TOKEN:
      COOKIE:
      REDIS_PORT: ${REDIS_PORT:-6381}
    restart: unless-stopped
    links:
      - redis
  redis:
    image: "redis:alpine@sha256:519f0189dfdee3bc0bad61fb265fe73d864b5c64020e6579ad48a45c49965635"
    environment:
      REDIS_PORT: ${REDIS_PORT:-6381}
    command: redis-server --port ${REDIS_PORT:-6381} --appendonly yes
    expose:
      - "${REDIS_PORT:-6381}"
    ports:
      - "127.0.0.1:${REDIS_PORT:-6381}:${REDIS_PORT:-6381}"
    sysctls:
      net.core.somaxconn: 1024
    restart: unless-stopped
    volumes:
      - ./redis-data:/data:rw
